###############################################################################
#
#   Config file for this Snakemake pipeline.
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: maciej.bak@unibas.ch
#   CREATED: 23-11-2019
#   LICENSE: GPL v3.0
#
###############################################################################
---

# path to the directory with all the scripts and executable files
src_dir: "src"

# path for the result directory
output_dir: "output_dir"

# path to the design table with sample/bam information
design_file: "sample_design_table.tsv"

# path to the genomic sequence in FASTA format
genome: "resources/Homo_sapiens.GRCh38.dna.primary_assembly.fa"

# path to the table with effective genome sizes
effective_genome_sizes: "effective_genome_sizes.tsv"

# genome version
# available options are row names from the effective genome sizes table
genome_version: "GRCh38"

...
